# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installFromWheel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstallWHLDialog(object):
    def setupUi(self, InstallWHLDialog):
        InstallWHLDialog.setObjectName("InstallWHLDialog")
        InstallWHLDialog.resize(491, 451)
        InstallWHLDialog.setMinimumSize(QtCore.QSize(491, 451))
        InstallWHLDialog.setMaximumSize(QtCore.QSize(491, 451))
        self.layoutWidget = QtWidgets.QWidget(InstallWHLDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 9, 471, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.package_name = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.package_name.sizePolicy().hasHeightForWidth())
        self.package_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.package_name.setFont(font)
        self.package_name.setStyleSheet("color: rgb(0, 170, 255);")
        self.package_name.setAlignment(QtCore.Qt.AlignCenter)
        self.package_name.setObjectName("package_name")
        self.verticalLayout_3.addWidget(self.package_name)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.WheelMetadata = QtWidgets.QTreeWidget(self.layoutWidget)
        self.WheelMetadata.setAutoExpandDelay(0)
        self.WheelMetadata.setIndentation(10)
        self.WheelMetadata.setItemsExpandable(True)
        self.WheelMetadata.setWordWrap(True)
        self.WheelMetadata.setExpandsOnDoubleClick(True)
        self.WheelMetadata.setObjectName("WheelMetadata")
        self.WheelMetadata.header().setVisible(False)
        self.horizontalLayout_5.addWidget(self.WheelMetadata)
        self.ConsoleOutput = QtWidgets.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ConsoleOutput.sizePolicy().hasHeightForWidth())
        self.ConsoleOutput.setSizePolicy(sizePolicy)
        self.ConsoleOutput.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                         "color: rgb(97, 255, 62);")
        self.ConsoleOutput.setReadOnly(True)
        self.ConsoleOutput.setObjectName("ConsoleOutput")
        self.horizontalLayout_5.addWidget(self.ConsoleOutput)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnInstall = QtWidgets.QPushButton(self.layoutWidget)
        self.btnInstall.setEnabled(False)
        self.btnInstall.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInstall.setObjectName("btnInstall")
        self.verticalLayout_5.addWidget(self.btnInstall)
        self.btnBack = QtWidgets.QPushButton(self.layoutWidget)
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBack.setObjectName("btnBack")
        self.verticalLayout_5.addWidget(self.btnBack)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.retranslateUi(InstallWHLDialog)
        QtCore.QMetaObject.connectSlotsByName(InstallWHLDialog)

    def retranslateUi(self, InstallWHLDialog):
        _translate = QtCore.QCoreApplication.translate
        InstallWHLDialog.setWindowTitle(
            _translate(
                "InstallWHLDialog",
                "Install packages from wheel"))
        self.label_4.setText(
            _translate(
                "InstallWHLDialog",
                "Install package from wheel"))
        self.label_3.setText(_translate("InstallWHLDialog", "Select package"))
        self.toolButton.setText(_translate("InstallWHLDialog", "..."))
        self.package_name.setText(
            _translate(
                "InstallWHLDialog",
                "<html><head/><body><p>package_name</p></body></html>"))
        self.btnInstall.setText(_translate("InstallWHLDialog", "Install"))
        self.btnBack.setText(_translate("InstallWHLDialog", "Go Back"))
