# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(391, 252)
        mainWindow.setMinimumSize(QtCore.QSize(391, 252))
        mainWindow.setMaximumSize(QtCore.QSize(392, 252))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.radioPy3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPy3.setGeometry(QtCore.QRect(221, 66, 66, 17))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.radioPy3.sizePolicy().hasHeightForWidth())
        self.radioPy3.setSizePolicy(sizePolicy)
        self.radioPy3.setObjectName("radioPy3")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioPy3)
        self.radioPy2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPy2.setGeometry(QtCore.QRect(110, 66, 66, 17))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.radioPy2.sizePolicy().hasHeightForWidth())
        self.radioPy2.setSizePolicy(sizePolicy)
        self.radioPy2.setChecked(True)
        self.radioPy2.setObjectName("radioPy2")
        self.buttonGroup_2.addButton(self.radioPy2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 371, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(200, 200, 180, 23))
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNext.setObjectName("btnNext")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(12, 100, 369, 19))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.radioInstall = QtWidgets.QRadioButton(self.centralwidget)
        self.radioInstall.setGeometry(QtCore.QRect(120, 124, 123, 17))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.radioInstall.sizePolicy().hasHeightForWidth())
        self.radioInstall.setSizePolicy(sizePolicy)
        self.radioInstall.setChecked(True)
        self.radioInstall.setObjectName("radioInstall")
        self.buttonGroup = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioInstall)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(13, 200, 181, 23))
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setObjectName("btnExit")
        self.radioUpdate = QtWidgets.QRadioButton(self.centralwidget)
        self.radioUpdate.setGeometry(QtCore.QRect(121, 147, 146, 17))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.radioUpdate.sizePolicy().hasHeightForWidth())
        self.radioUpdate.setSizePolicy(sizePolicy)
        self.radioUpdate.setObjectName("radioUpdate")
        self.buttonGroup.addButton(self.radioUpdate)
        self.radioUninstall = QtWidgets.QRadioButton(self.centralwidget)
        self.radioUninstall.setGeometry(QtCore.QRect(121, 170, 151, 17))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.radioUninstall.sizePolicy().hasHeightForWidth())
        self.radioUninstall.setSizePolicy(sizePolicy)
        self.radioUninstall.setObjectName("radioUninstall")
        self.buttonGroup.addButton(self.radioUninstall)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.actionRefresh = QtWidgets.QAction(mainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "PIP GUI"))
        self.label_5.setText(
            _translate(
                "mainWindow",
                "PIPGUI - GUI Based Pip Package Installer"))
        self.radioPy3.setText(_translate("mainWindow", "Python 3"))
        self.radioPy2.setText(_translate("mainWindow", "Python 2"))
        self.label_3.setText(
            _translate(
                "mainWindow",
                "<html><head/><body><p><span style=\" text-decoration: underline;\">Select the Python runtime</span></p></body></html>"))
        self.btnNext.setText(_translate("mainWindow", "Next"))
        self.label_4.setText(
            _translate(
                "mainWindow",
                "<html><head/><body><p><span style=\" text-decoration: underline;\">Select action</span></p></body></html>"))
        self.radioInstall.setText(
            _translate(
                "mainWindow",
                "Install new packages"))
        self.btnExit.setText(_translate("mainWindow", "Exit"))
        self.radioUpdate.setText(
            _translate(
                "mainWindow",
                "Update existing packages"))
        self.radioUninstall.setText(
            _translate(
                "mainWindow",
                "Uninstall existing packages"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionRefresh.setText(_translate("mainWindow", "Refresh lists"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
